name: Build
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - "**/README.md"
      - "*.sh"
      - "*.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bad_proxy_go
        shell: bash
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          path: bad_proxy_go

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: bad_proxy_go/go.mod

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh bad_proxy_go
        env:
          CGO_ENABLE: 0
