name: Build Artifact
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.yml"
      - "**.md"
      - "**.sh"
      - "**.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: bad_proxy_go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: bad_proxy_go/go.mod
      - name: Build
        run: |
          cd bad_proxy_go
          chmod +x ./build.sh
          ./build.sh ${{ vars.DIST_NAME }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: bad_proxy_go/dist
          overwrite: true