name: Build Artifact
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.yml"
      - "**.md"
      - "**.sh"
      - "**.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: bad-proxy-core
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: bad-proxy-core/go.mod
      - name: Build
        run: |
          cd bad-proxy-core
          chmod +x ./build.sh
          ./build.sh ${{ vars.DIST_NAME }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bad-proxy-core
          path: bad-proxy-core/dist
          overwrite: true
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'bad-proxy-core/dist/**/*.tar.gz, bad-proxy-core/dist/**/*.zip'
