name: Build Artifact
on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - "**.yml"
      - "**.md"
      - "**.sh"
      - "**.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: bad_proxy_go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: bad_proxy_go/go.mod
      - name: Build
        run: |
          cd bad_proxy_go
          go build -o bad_proxy
