name: Release Distribution
on:
  push:
    tags:
      - "v1.**"
    paths-ignore:
      - "**.yml"
      - "**.md"
      - "**.sh"
      - "**.json"
      - ".gitignore"
jobs:
  release_github:
    name: Release for github
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bad_proxy_go
        shell: bash
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: bad_proxy_go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: bad_proxy_go/go.mod
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh ${{ vars.DIST_NAME }}
      - name: Release and upload assets
        run: gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes --latest ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_dockerhub:
    name: Release for dockerhub
    runs-on: ubuntu-latest
    needs: release_github
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: wwricu/bad_proxy_go:${{ github.ref_name }}
      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: wwricu/bad_proxy_go:latest